In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [18]:

train_df = pd.read_csv(r"C:\Users\Admin\Downloads\homeprices.xls")
train_df.head()


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [19]:
import math
bedrooms_mean = math.floor(train_df.bedrooms.mean())
train_df.bedrooms = train_df.bedrooms.fillna(bedrooms_mean)
train_df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [20]:
train_X = train_df.drop(['price'], axis=1)
train_Y = train_df.price
train_X,train_Y

(   area  bedrooms  age
 0  2600       3.0   20
 1  3000       4.0   15
 2  3200       4.0   18
 3  3600       3.0   30
 4  4000       5.0    8
 5  4100       6.0    8,
 0    550000
 1    565000
 2    610000
 3    595000
 4    760000
 5    810000
 Name: price, dtype: int64)

In [21]:
# Train model
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(train_X, train_Y)

LinearRegression()

In [23]:
model

LinearRegression()

In [24]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [25]:
model.intercept_

np.float64(221323.00186540443)

In [26]:
#predict home price
price_predicated = model.predict([[3000, 3, 40]])
price_predicated_manually = 3000*model.coef_[0] + 3 * model.coef_[1] + 40 * model.coef_[2] + model.intercept_
price_predicated, price_predicated_manually

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


(array([498408.25158031]), np.float64(498408.2515803069))

In [28]:
price_predicated

array([498408.25158031])

In [29]:
# Score
model.score(train_X, train_Y)

0.9550196399325818

In [30]:
import pickle
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [31]:
# import trained model using pickle
with open('model_pickle', 'rb') as f:
    pickle_model = pickle.load(f)
price_predicated_pickle = pickle_model.predict([[3000, 3, 40]])
price_predicated_pickle

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [32]:
# save model joblib
import joblib
joblib.dump(model, 'model_joblib')

['model_joblib']

In [33]:
# import trained model using pickle
joblib_model = joblib.load('model_joblib')
price_predicated_joblib = joblib_model.predict([[3000, 3, 40]])
price_predicated_joblib

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])